name: deploy-main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

    - name: Configure Docker for GCP
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/ori-saude/ori-saude-api/ori-saude-api:latest .

    - name: Push Docker image
      run: |
        docker push us-central1-docker.pkg.dev/ori-saude/ori-saude-api/ori-saude-api:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ori-saude-api \
          --image us-central1-docker.pkg.dev/ori-saude/ori-saude-api/ori-saude-api:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --update-env-vars FIREBASE_CREDENTIALS="${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
