name: Deploy Go Backend to Cloud Run

on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT: ori-saude # ID do projeto GCP
      CLOUD_RUN_SERVICE: ori-saude-api
      REGION: us-central1 # região do Cloud Run
      REPOSITORY: ori-saude-api # nome do Artifact Registry Docker

    steps:
    # 1️⃣ Puxar o código do repositório
    - name: Checkout código
      uses: actions/checkout@v3

    # 2️⃣ Configurar gcloud e autenticar a service account
    - name: Configure gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    # 3️⃣ Autenticar Docker com Artifact Registry
    - name: Authenticate Docker with Artifact Registry
      run: gcloud auth configure-docker us-docker.pkg.dev

    # 4️⃣ Build da imagem Docker e push para Artifact Registry
    - name: Build and push Docker image
      run: |
        IMAGE="us-docker.pkg.dev/${GCP_PROJECT}/${REPOSITORY}/${CLOUD_RUN_SERVICE}:${GITHUB_SHA}"
        docker build -t $IMAGE .
        docker push $IMAGE

    # 5️⃣ Deploy automático no Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${CLOUD_RUN_SERVICE} \
          --image "us-docker.pkg.dev/${GCP_PROJECT}/${REPOSITORY}/${CLOUD_RUN_SERVICE}:${GITHUB_SHA}" \
          --platform managed \
          --region ${REGION} \
          --allow-unauthenticated \
          --set-env-vars FIREBASE_CREDENTIALS_JSON="${{ secrets.FIREBASE_CREDENTIALS_JSON }}"
