name: Deploy to Cloud Run

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Deploy to Cloud Run (direct source)
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ori-saude-api
        region: us-central1
        source: .
        project_id: ori-saude
