name: Deploy Go Backend to Cloud Run

on:
  push:
    branches:
    - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT: ori-saude
      CLOUD_RUN_SERVICE: ori-saude-api
      REGION: us-central1

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configure gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Build Docker image
      run: |
        IMAGE="gcr.io/${GCP_PROJECT}/${CLOUD_RUN_SERVICE}:${GITHUB_SHA}"
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${CLOUD_RUN_SERVICE} \
          --image "gcr.io/${GCP_PROJECT}/${CLOUD_RUN_SERVICE}:${GITHUB_SHA}" \
          --platform managed \
          --region ${REGION} \
          --allow-unauthenticated \
          --set-env-vars FIREBASE_CREDENTIALS_JSON="${{ secrets.FIREBASE_CREDENTIALS_JSON }}"
