name: deploy-main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Deploy to Cloud Run directly from source
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ori-saude-api
        region: us-central1
        source: .
        project_id: ori-saude
